In [1]:
import torch

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX
MATRIX.ndim
MATRIX.shape


torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape


torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.8913, 0.2051, 0.6871, 0.1194],
        [0.1916, 0.8073, 0.7334, 0.8583],
        [0.9274, 0.4577, 0.2812, 0.8024]])

In [28]:
random_image_size_tensor = torch.rand(size=(3, 244, 244)) #height, width, color channels (RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [29]:
# Float 32 tensor
float_32_tensor = torch.tensor([3,6,9], 
                            dtype=torch.float32,
                            device=None,
                            requires_grad=True)
float_32_tensor

tensor([3., 6., 9.], requires_grad=True)

In [32]:
tensor = torch.tensor([1,2,3])
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 586 μs, sys: 3.72 ms, total: 4.3 ms
Wall time: 38.7 ms


tensor(14)

In [34]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [36]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [40]:
z = x.view(1, 9)
# View is similar to reshape, but it can handle non-contiguous tensors
# View is faster than reshape
# View is more memory efficient than reshape
# View is more flexible than reshape
# View is more intuitive than reshape
# View is more readable than reshape
# View is more pythonic than reshape
z[:,0]=33
z, x

(tensor([[33.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([33.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [51]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x, x ], dim=1)
x_stacked, x_stacked.shape

(tensor([[33., 33., 33., 33., 33.],
         [ 2.,  2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.,  9.]]),
 torch.Size([9, 5]))